create table if not exists PUBLIC.WORK_ROLE
(
    ROLE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    TITLE         VARCHAR(50) not null,
    DESCRIPTION   VARCHAR(50) not null,
    SALARY        DOUBLE      not null,
    CREATION_DATE DATE        not null
);